import type { BtrAlert, BtrHolding, BtrReport } from '../types';
import { generateId } from './utils';

export const SEED_BTR_ALERTS: BtrAlert[] = [
  // March 8, 2026 Trade Alerts
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'BABA', description: 'Alibaba — up to 2/3, around $114', price: 114, date: '2026-03-04', sector: 'Emerging Markets' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'CVX', description: 'Chevron — back to 1/3, at $192', closingPnl: '+32%', date: '2026-03-06', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'PTEN', description: 'Patterson-UTI Energy — near $9', closingPnl: '+5%', date: '2026-03-02', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'OXY', description: 'Occidental Petroleum — back to 1/3, near $56', closingPnl: '+15%', date: '2026-03-05', sector: 'Equities' },
  // Recent Sells (March)
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'VIXY', description: 'ProShares VIX ETF', closingPnl: '-10%', date: '2026-03-03', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'AR', description: 'Antero Resources', closingPnl: '+29%', date: '2026-03-03', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'XOP', description: 'S&P Oil & Gas Exploration ETF', closingPnl: '+22%', date: '2026-03-02', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'VIXY', description: 'ProShares VIX Short-Term Futures ETF', closingPnl: '+15%', date: '2026-03-02', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'USO', description: 'US Oil Fund', closingPnl: '+25%', date: '2026-03-02', sector: 'Equities' },
  // Recent Sells (February)
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'USO', description: 'US Oil Fund', closingPnl: '+15%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'BMY', description: 'Bristol Myers Squib', closingPnl: '+57%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'FAZ', description: 'UltraShort Financials ETF', closingPnl: '+6%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'FCX', description: 'Freeport-McMoran Inc', closingPnl: '+65%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'OXY', description: 'Occidental Petroleum', closingPnl: '+21%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'LYB', description: 'Lyondell', closingPnl: '+29%', date: '2026-02-11', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'ODFL', description: 'Old Dominion', closingPnl: '+43%', date: '2026-01-27', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'VALE', description: 'Vale SA', closingPnl: '+74%', date: '2026-01-27', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'SLV', description: 'Silver ETF', closingPnl: '+206%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'GDX', description: 'Gold Miners ETF', closingPnl: '+138%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'ARGT', description: 'Argentina ETF', closingPnl: '+36%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'SRUUF', description: 'Sprott Physical Uranium Trust', closingPnl: '+39%', date: '2026-01-25', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'PALL', description: 'Physical Palladium ETF', closingPnl: '+85%', date: '2026-01-23', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'CNR', description: 'Core Natural Resources', closingPnl: '+34%', date: '2026-01-23', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'ALB', description: 'Albemarle', closingPnl: '+152%', date: '2026-01-24', sector: 'Equities' },
  // Recent Buys
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'WDAY', description: 'Workday', price: 114, date: '2026-02-27', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'VIXY', description: 'ProShares VIX Short-Term Futures ETF', date: '2026-02-12', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'PLTM', description: 'GraniteShares Platinum ETF', date: '2026-02-12', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'CNR', description: 'Core Natural Resources', date: '2026-02-09', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'IBIT', description: 'iShares Bitcoin Trust ETF', date: '2026-02-06', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'PYPL', description: 'PayPal', date: '2026-02-05', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'SLV', description: 'Silver ETF', date: '2026-02-08', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'IBIT', description: 'iShares Bitcoin Trust', date: '2026-01-25', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'PTEN', description: 'Patterson-Uti Energy', date: '2025-12-30', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'NKE', description: 'Nike Inc.', date: '2025-12-19', sector: 'Growth' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'BABA', description: 'Alibaba', date: '2025-12-15', sector: 'Emerging Markets' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'FAZ', description: 'UltraShort Financials ETF', date: '2025-12-09', sector: 'Financials' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'LULU', description: 'Lululemon Athletics', date: '2025-11-14', sector: 'Consumer' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'CMG', description: 'Chipotle', date: '2025-11-11', sector: 'Consumer' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'ADBE', description: 'Adobe', date: '2025-11-04', sector: 'Tech' },
];

export const SEED_BTR_HOLDINGS: BtrHolding[] = [
  // Short-Term (30-60 Days)
  { id: generateId(), position: '3/3', ticker: 'MSOS', description: 'US Cannabis ETF', sector: 'Value', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'KWEB', description: 'China Internet ETF', sector: 'Emerging Markets', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'IMPUY', description: 'Impala Platinum', sector: 'Commodities', timeframe: 'short' },
  { id: generateId(), position: '2/3', ticker: 'FAZ', description: 'Direxion Financial Bear 3X', sector: 'Financials', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'RIO', description: 'Rio Tinto', sector: 'Commodities', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'XOP', description: 'Oil & Gas E&P ETF', sector: 'Oil & Gas', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'TGT', description: 'Target', sector: 'Retail', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'ODFL', description: 'Old Dominion', sector: 'Transport', timeframe: 'short' },
  { id: generateId(), position: '1/2', ticker: 'DEO', description: 'Diageo', sector: 'Consumer', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'LYB', description: 'Lyondell', sector: 'Chemicals', timeframe: 'short' },
  { id: generateId(), position: '2/3', ticker: 'ADBE', description: 'Adobe', sector: 'Tech', timeframe: 'short' },
  // Long-Term (12-24 Month View)
  { id: generateId(), position: '1/3', ticker: 'URNM', description: 'Uranium Miner ETF', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'SRUUF', description: 'Sprott Physical Uranium Trust', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/2', ticker: 'FCG', description: 'First Trust Nat Gas ETF', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'FCX', description: 'Freeport McMoran', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'AA', description: 'Alcoa', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'CNR', description: 'Core Natural Resources', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'RRC', description: 'Range Resources', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'AR', description: 'Antero Resources', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '3/3', ticker: 'SLB', description: 'Schlumberger', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'WFRD', description: 'Weatherford', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'OXY', description: 'Occidental Petroleum', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'OKE', description: 'ONEOK', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'CVX', description: 'Chevron Energy', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '3/3', ticker: 'NKE', description: 'Nike Inc.', sector: 'Growth', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'GLRE', description: 'Greenlight Capital', sector: 'Value', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'EWU', description: 'United Kingdom ETF', sector: 'Non-US Developed', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'EWZ', description: 'Brazil ETF', sector: 'Emerging Markets', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'BABA', description: 'Alibaba Group', sector: 'Emerging Markets', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'INDA', description: 'iShares MSCI India', sector: 'Emerging Markets', timeframe: 'long' },
];

export const SEED_BTR_REPORT: BtrReport = {
  id: generateId(),
  date: '2026-03-08',
  title: 'Turning Point - March 8, 2026',
  keyThemes: [
    'Double whammy: Iran war + weak NFP (-92K payrolls vs +55K expected). Biggest payroll decline since Oct 2025.',
    'Credit risk spreading: BlackRock halts outflows, BDC NAV discounts 30-50%, private credit defaults at 5.8% TTM (Fitch record). $2-3T shadow banking beast finally meeting a credit cycle.',
    'FAZ ETF +45% off Jan lows — credit short bet paying off. Even IG CDS blowing out.',
    'AI job disruption narrative flipped: from "augments, creates net jobs" (mid-2025) to "guarded anxiety" (early 2026). Hiring froze in software, finance, consulting. $650B+ AI capex funds labor savings.',
    'Yield curve flattening: initially bull flattening (AI/labor market), now bear flattening (Iran/oil). Fed in conundrum — wants to cut but oil above $85-90.',
    'Hormuz Strait disruption: 17 mb/d Persian Gulf supply shock — 17x bigger than Russia April 2022 peak. SoH flows down 90%. Brent could blast over $100 if no progress.',
    'Gasoline +43% off December price. At the pump = $180M/day cost, $65B annualized. Eats 65% of OBBB tax windfall.',
    'Bloomberg Commodity Index (BCOM) +22% since December, pushing near record highs. Energy shocks + tariff pass-throughs driving inflation re-acceleration.',
    'PPI heat coming Wednesday March 18 — key inflation data. Jan headline +0.5% MoM, core services exploding +0.8%.',
    'OBBB fiscal windfall gone: $115B+ war costs ($65B + $50B Pentagon supplemental) exceeds entire annual tax cut benefit.',
    'Trade Alert: Buy 1/3 BABA around $114, up to 2/3. Sell 1/3 CVX at $192. Sell All PTEN near $9. Sell 1/3 OXY near $56.',
    'Taking profits on energy basket — selling into geopolitical bid. Lightening commodities after massive runs (SLV +206%, GDX +138%, ALB +152%, PALL +85%).',
    'Betting markets: 79% chance Iran conflict extends past June 30. Only 5% chance it ends by March 7.',
  ],
  performance: {
    hc3m: '+17.6%',
    hc12m: '+31.1%',
    sp3m: '+1.0%',
    sp12m: '+15.4%',
    realizedSells12m: '+29.5%',
    hedgeRealized12m: '+27.2%',
  },
  allocation: {
    'Energy': 30,
    'Materials': 18,
    'Tech': 15,
    'Emerging Markets': 12,
    'Precious Metals': 4,
    'Financials': 5,
    'Consumer Disc.': 3,
    'Commodities': 8,
    'Value': 1,
  },
  notes: '',
};
