import type { BtrAlert, BtrHolding, BtrReport } from '../types';
import { generateId } from './utils';

export const SEED_BTR_ALERTS: BtrAlert[] = [
  // Recent Sells
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'USO', description: 'US Oil Fund', closingPnl: '+15%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'BMY', description: 'Bristol Myers Squib', closingPnl: '+55%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'FAZ', description: 'UltraShort Financials ETF', closingPnl: '+6%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'FCX', description: 'Freeport-McMoran Inc', closingPnl: '+65%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'OXY', description: 'Occidental Petroleum', closingPnl: '+2%', date: '2026-02-24', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'LYB', description: 'Lyondell', closingPnl: '+29%', date: '2026-02-11', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'ODFL', description: 'Old Dominion', closingPnl: '+43%', date: '2026-01-27', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'VALE', description: 'Vale SA', closingPnl: '+74%', date: '2026-01-27', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'SLV', description: 'Silver ETF', closingPnl: '+206%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'GDX', description: 'Gold Miners ETF', closingPnl: '+138%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'ARGT', description: 'Argentina ETF', closingPnl: '+36%', date: '2026-01-26', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'SRUUF', description: 'Sprott Physical Uranium Trust', closingPnl: '+39%', date: '2026-01-25', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'PALL', description: 'Physical Palladium ETF', closingPnl: '+85%', date: '2026-01-23', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: '1/3', ticker: 'CNR', description: 'Core Natural Resources', closingPnl: '+34%', date: '2026-01-23', sector: 'Equities' },
  { id: generateId(), action: 'Sell', size: 'All', ticker: 'ALB', description: 'Albemarle', closingPnl: '+152%', date: '2026-01-24', sector: 'Equities' },
  // Recent Buys
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'WDAY', description: 'Workday', price: 114, date: '2026-02-27', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'VIXY', description: 'ProShares VIX Short-Term Futures ETF', date: '2026-02-12', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'PLTM', description: 'GraniteShares Platinum ETF', date: '2026-02-12', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'CNR', description: 'Core Natural Resources', date: '2026-02-09', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'IBIT', description: 'iShares Bitcoin Trust ETF', date: '2026-02-06', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'PYPL', description: 'PayPal', date: '2026-02-05', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/4', ticker: 'SLV', description: 'Silver ETF', date: '2026-02-08', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'IBIT', description: 'iShares Bitcoin Trust', date: '2026-01-25', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'PTEN', description: 'Patterson-Uti Energy', date: '2025-12-30', sector: 'Equities' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'NKE', description: 'Nike Inc.', date: '2025-12-19', sector: 'Growth' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'BABA', description: 'Alibaba', date: '2025-12-15', sector: 'Emerging Markets' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'FAZ', description: 'UltraShort Financials ETF', date: '2025-12-09', sector: 'Financials' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'LULU', description: 'Lululemon Athletics', date: '2025-11-14', sector: 'Consumer' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'CMG', description: 'Chipotle', date: '2025-11-11', sector: 'Consumer' },
  { id: generateId(), action: 'Buy', size: '1/3', ticker: 'ADBE', description: 'Adobe', date: '2025-11-04', sector: 'Tech' },
];

export const SEED_BTR_HOLDINGS: BtrHolding[] = [
  // Short-Term (30-60 Days)
  { id: generateId(), position: '3/3', ticker: 'MSOS', description: 'US Cannabis ETF', sector: 'Value', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'KWEB', description: 'China Internet ETF', sector: 'Emerging Markets', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'IMPUY', description: 'Impala Platinum', sector: 'Commodities', timeframe: 'short' },
  { id: generateId(), position: '2/3', ticker: 'FAZ', description: 'Direxion Financial Bear 3X', sector: 'Financials', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'RIO', description: 'Rio Tinto', sector: 'Commodities', timeframe: 'short' },
  { id: generateId(), position: '2/3', ticker: 'XOP', description: 'Oil & Gas E&P ETF', sector: 'Oil & Gas', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'TGT', description: 'Target', sector: 'Retail', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'ODFL', description: 'Old Dominion', sector: 'Transport', timeframe: 'short' },
  { id: generateId(), position: '1/2', ticker: 'DEO', description: 'Diageo', sector: 'Consumer', timeframe: 'short' },
  { id: generateId(), position: '1/3', ticker: 'LYB', description: 'Lyondell', sector: 'Chemicals', timeframe: 'short' },
  { id: generateId(), position: '2/3', ticker: 'ADBE', description: 'Adobe', sector: 'Tech', timeframe: 'short' },
  // Long-Term (12-24 Month View)
  { id: generateId(), position: '1/3', ticker: 'URNM', description: 'Uranium Miner ETF', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'SRUUF', description: 'Sprott Physical Uranium Trust', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/2', ticker: 'FCG', description: 'First Trust Nat Gas ETF', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'FCX', description: 'Freeport McMoran', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'AA', description: 'Alcoa', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'CNR', description: 'Core Natural Resources', sector: 'Commodities', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'RRC', description: 'Range Resources', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '3/3', ticker: 'AR', description: 'Antero Resources', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '3/3', ticker: 'SLB', description: 'Schlumberger', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'WFRD', description: 'Weatherford', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'OXY', description: 'Occidental Petroleum', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'OKE', description: 'ONEOK', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'CVX', description: 'Chevron Energy', sector: 'Oil & Gas', timeframe: 'long' },
  { id: generateId(), position: '3/3', ticker: 'NKE', description: 'Nike Inc.', sector: 'Growth', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'GLRE', description: 'Greenlight Capital', sector: 'Value', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'EWU', description: 'United Kingdom ETF', sector: 'Non-US Developed', timeframe: 'long' },
  { id: generateId(), position: '2/3', ticker: 'EWZ', description: 'Brazil ETF', sector: 'Emerging Markets', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'BABA', description: 'Alibaba Group', sector: 'Emerging Markets', timeframe: 'long' },
  { id: generateId(), position: '1/3', ticker: 'INDA', description: 'iShares MSCI India', sector: 'Emerging Markets', timeframe: 'long' },
];

export const SEED_BTR_REPORT: BtrReport = {
  id: generateId(),
  date: '2026-03-01',
  title: 'Turning Point - March 1, 2026',
  keyThemes: [
    'Credit risk > PPI risk — high impact signals. BDCs and private equity taking the plunge.',
    'SOFR futures pricing in more rate cuts. 10-year yields drop to October lows.',
    'Goldman warning: financial system creeping toward another potential catastrophe.',
    'Trade Alert: Buy 1/4 WDAY around $114 — fallen angel, CAT-5 capitulation buy.',
    'Trade Alert: Sell 1/3 FCX at $65.',
    'Sell 1/3 BMY near $62.',
    'Looking to lighten energy exposure and sell into the geopolitical bid (Iran).',
    'Software showing tradeable bottom signs — WDAY off 60% in 12 months, IGV back above 200wma.',
    'Emerging Markets: Korea & Taiwan account for 80% of EEM outperformance YTD (memory trade).',
    'Iran strikes — US starts another war. Oil not in extreme backwardation. Brent curve not steep.',
    'AI singularity trade: markets struggling to price in AI impact. Software credit risk broadening.',
    'Midterm election year pattern: S&P 500 avg -0.31% first 3 months, -0.49% first 6 months.',
    'CRM deeply undervalued at ~10x EV/FCFE, ~20x GAAP P/E — software dips = buy opportunity.',
  ],
  performance: {
    hc3m: '+17.6%',
    hc12m: '+31.1%',
    sp3m: '+1.0%',
    sp12m: '+15.4%',
    realizedSells12m: '+29.5%',
    hedgeRealized12m: '+27.2%',
  },
  allocation: {
    'Energy': 35,
    'Materials': 18,
    'Tech': 18,
    'Emerging Markets': 9,
    'Precious Metals': 4,
    'Financials': 3,
    'Consumer Disc.': 3,
    'Value': 1,
    'Telecom': 0,
  },
  notes: '',
};
